name: Youtube Downloader

on:
  workflow_dispatch:
    inputs:
      url:
        description: URL from youtube
        required: true
        type: string
  push:
    branches:
      - main

permissions: 
  contents: write

jobs:
  Youtube-DL:
    runs-on: ubuntu-latest
    steps:
      - name: Setup yt-dlp
        uses: AnimMouse/setup-yt-dlp@v3
        
      - name: Setup yt-dlp YouTube cookies
        uses: AnimMouse/setup-yt-dlp/cookies@v3
        with:
          cookies: ${{ secrets.YOUTUBE_COOKIES }}

      - name: Download from youtube url
        run: yt-dlp ${{ inputs.url }}

      - name: Update yt-dlp YouTube cookies
        uses: AnimMouse/setup-yt-dlp/cookies/update@v3
        with:
          cookies_secret_name: YOUTUBE_COOKIES
          token: ${{ secrets.GH_PAT }}

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to Repository
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "⬇️ Youtube URL: ${{ inputs.url }}"
          git push
      
